/*
 * 자료실 요청
 * */
export const GET_MANY_REFERENCE_REQUEST = 'GET_MANY_REFERENCE_REQUEST';
export const GET_MANY_REFERENCE_SUCCESS = 'GET_MANY_REFERENCE_SUCCESS';
export const GET_MANY_REFERENCE_FAILURE = 'GET_MANY_REFERENCE_FAILURE';

/*
 * 자료실 상세 가져오기
 * */
export const GET_ONE_REFERENCE_REQUEST = 'GET_ONE_REFERENCE_REQUEST';
export const GET_ONE_REFERENCE_SUCCESS = 'GET_ONE_REFERENCE_SUCCESS';
export const GET_ONE_REFERENCE_FAILURE = 'GET_ONE_REFERENCE_FAILURE';

/*
 * 자료실 사용하기
 * */
export const POST_USE_REFERENCE_REQUEST = 'POST_USE_REFERENCE_REQUEST';
export const POST_USE_REFERENCE_SUCCESS = 'POST_USE_REFERENCE_SUCCESS';
export const POST_USE_REFERENCE_FAILURE = 'POST_USE_REFERENCE_FAILURE';
