/*
 * 활용사례 요청
 * */
export const GET_MANY_USECASE_REQUEST = 'GET_MANY_USECASE_REQUEST';
export const GET_MANY_USECASE_SUCCESS = 'GET_MANY_USECASE_SUCCESS';
export const GET_MANY_USECASE_FAILURE = 'GET_MANY_USECASE_FAILURE';

/*
 * 활용사례 상세 가져오기
 * */
export const GET_ONE_USECASE_REQUEST = 'GET_ONE_USECASE_REQUEST';
export const GET_ONE_USECASE_SUCCESS = 'GET_ONE_USECASE_SUCCESS';
export const GET_ONE_USECASE_FAILURE = 'GET_ONE_USECASE_FAILURE';
